"""
vendor_voidcore.py — copy Void Core's runtime into vendor/voidcore/.

Why vendoring: the packaged app must ship with everything (a user is never
asked to pip install), CI builds this repo without the sibling VoidCore
checkout, and the public void-core mirror can lag the local repo — vendoring
from the LOCAL repo ships exactly the version that was tested here.

The copy preserves VoidCore's repo layout, because the voidcore package
resolves its binding/holidays/layers and libvoidcore.dll *relative to its own
location* (ROOT = two levels up from voidcore/__init__.py). hormiga_core adds
vendor/voidcore to sys.path when the editable install isn't present.

Re-run after updating VoidCore:  python scripts/vendor_voidcore.py
Native libs: whichever core/build/bin libraries exist locally are copied —
on this machine that is the Windows DLL; mac/linux packaged builds stay
gracefully degraded until their libs are built and vendored too.
"""
from __future__ import annotations

import shutil
import sys
from pathlib import Path

HORMIGA = Path(__file__).resolve().parent.parent
VOIDCORE = HORMIGA.parent / "VoidCore"
DEST = HORMIGA / "vendor" / "voidcore"

# (source relative to VoidCore repo, copy-if-matching glob)
FILES = [
    ("voidcore", "*.py"),
    ("bindings/python", "voidcore.py"),
    ("holidays/localjson", "*.py"),
    ("scry", "*.py"),
    ("temper", "*.py"),
    ("reduce", "*.py"),
    ("core/build/bin", "libvoidcore.*"),   # .dll / .so / .dylib — whatever is built
]
EXCLUDE = ("_test.py", "_example.py")


def main() -> int:
    if not VOIDCORE.is_dir():
        print(f"VoidCore repo not found at {VOIDCORE}", file=sys.stderr)
        return 1
    if DEST.exists():
        shutil.rmtree(DEST)
    copied = 0
    for rel, pattern in FILES:
        src_dir = VOIDCORE / rel
        if not src_dir.is_dir():
            print(f"  skip (missing): {rel}")
            continue
        out_dir = DEST / rel
        out_dir.mkdir(parents=True, exist_ok=True)
        for f in sorted(src_dir.glob(pattern)):
            if f.name.endswith(EXCLUDE):
                continue
            shutil.copy2(f, out_dir / f.name)
            copied += 1
            print(f"  {rel}/{f.name}")
    (DEST / "VENDORED.md").write_text(
        "Vendored Void Core runtime (MIT, github.com/migriv24/void-core).\n"
        "Generated by scripts/vendor_voidcore.py — do not edit by hand;\n"
        "re-run the script after updating the VoidCore repo.\n",
        encoding="utf-8")
    print(f"vendored {copied} files -> {DEST}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
